# Generated by Django 5.1.6 on 2025-03-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/%Y_%m_%d/'),
        ),
    ]
