# Generated by Django 5.1.6 on 2025-03-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=65, verbose_name='Razão social')),
                ('nome_fantasia', models.CharField(max_length=65, verbose_name='Nome fantasia')),
                ('cnpj', models.CharField(max_length=17, verbose_name='CPF/CNPJ')),
                ('responsavel', models.CharField(max_length=100, verbose_name='Responsavel legal')),
                ('responsavel_cpf', models.CharField(max_length=15, verbose_name='CPF')),
                ('responsavel_data_nasc', models.DateField(verbose_name='Data de nascimento')),
                ('contato', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa?')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
