# Generated by Django 5.1.6 on 2025-05-10 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=65, verbose_name='Razão social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=65, verbose_name='Nome fantasia')),
                ('cnpj', models.CharField(max_length=17, verbose_name='CPF/CNPJ')),
                ('responsavel', models.CharField(blank=True, max_length=100, verbose_name='Responsavel legal')),
                ('responsavel_cpf', models.CharField(blank=True, max_length=15, verbose_name='CPF')),
                ('responsavel_data_nasc', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('contato', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('ativa', models.BooleanField(verbose_name='Ativa?')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='EmpresaContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato', models.CharField(max_length=20)),
                ('obs', models.TextField(blank=True, max_length=254, verbose_name='Observações')),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('data_atualizacao', models.DateField(auto_now=True, verbose_name='Data de atualização')),
                ('tipo_contato', models.CharField(choices=[('TR', 'Telefone residencial'), ('TC', 'Telefone comercial'), ('CP', 'Celular pessoal'), ('CC', 'Celular comercial'), ('WP', 'WhatsApp'), ('IT', 'Instagram'), ('FB', 'Facebook'), ('OT', 'Outros')], max_length=2, verbose_name='Tipo de contato')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Empresa.empresa')),
            ],
            options={
                'verbose_name': 'Empresa contato',
                'verbose_name_plural': 'Empresa contatos',
            },
        ),
        migrations.CreateModel(
            name='EmpresaEndereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('bairro', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=20)),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('complemento', models.TextField(blank=True, max_length=254)),
                ('ponto_referencia', models.TextField(blank=True, max_length=254)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Empresa.empresa')),
            ],
            options={
                'verbose_name': 'Empresa endereço',
                'verbose_name_plural': 'Empresa endereços',
            },
        ),
    ]
