# Generated by Django 5.1.6 on 2025-03-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='ativa',
            field=models.BooleanField(verbose_name='Ativa?'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=65, verbose_name='Nome fantasia'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='responsavel',
            field=models.CharField(blank=True, max_length=100, verbose_name='Responsavel legal'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='responsavel_cpf',
            field=models.CharField(blank=True, max_length=15, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='responsavel_data_nasc',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
    ]
