# Generated by Django 5.1.6 on 2025-03-12 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0002_empresacontato_empresaendereco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresacontato',
            options={'verbose_name': 'Empresa contato', 'verbose_name_plural': 'Empresa contatos'},
        ),
        migrations.AlterModelOptions(
            name='empresaendereco',
            options={'verbose_name': 'Empresa endereço', 'verbose_name_plural': 'Empresa endereços'},
        ),
    ]
