# Generated by Django 5.1.6 on 2025-04-21 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cliente', '0001_initial'),
        ('Estoque', '0002_alter_produto_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('detalhes', models.TextField(max_length=254)),
                ('data_cadastro', models.DateField(auto_now=True, verbose_name='Data de cadastro')),
                ('data_entrega', models.DateField(verbose_name='Data de entrega')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cliente.clientepessoa')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Estoque.localestoque')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Estoque.lote')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Pedido.pedido')),
            ],
            options={
                'verbose_name': 'Itens de pedido',
                'verbose_name_plural': 'Itens de pedidos',
            },
        ),
    ]
